import styled from '@emotion/styled';

export const LoaderWrap = styled.div`
  width: 380px;
  height: 100px;
  display: inline-block;
  overflow: hidden;
  /* background: #dddddd; */

  @keyframes ldio-2f13ynoe9ya {
    0% {
      transform: translate(132px, 2px);
    }
    33.33% {
      transform: translate(232px, 2px);
    }
    66.66% {
      transform: translate(172px, 52px);
    }
    100% {
      transform: translate(132px, 2px);
    }
  }

  .ldio-2f13ynoe9ya > div {
    transform: scale(0.8);
    transform-origin: 30px 30px;
  }

  .ldio-2f13ynoe9ya > div > div {
    animation: ldio-2f13ynoe9ya 1.4s linear infinite;
    position: absolute;
  }

  .ldio-2f13ynoe9ya > div > div .part1 {
    width: 32px;
    height: 32px;
    border-radius: 50%;
    border: 6px solid #c25452;
    background: #cfc7c0;
  }

  .ldio-2f13ynoe9ya > div > div .part2 {
    width: 8px;
    height: 31px;
    transform: rotate(-45deg);
    background: #c25452;
    border-radius: 0 0 8px 8px;
    position: absolute;
    top: 38px;
    left: 45px;
  }
  .loadingio-spinner-magnify-mn1ruqrggl {
  }
  .ldio-2f13ynoe9ya {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-2f13ynoe9ya div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
